name: booking
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0

  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5

  dartz: ^0.10.1
  dio: ^5.3.0
  dotted_line: ^3.2.2

  flutter:
    sdk: flutter
  flutter_gen: ^5.3.1
  flutter_pretty_dio_logger: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7

  get: ^4.6.5

  google_maps_flutter: ^2.4.0
  intl: ^0.18.1

  json_annotation: ^4.8.1

  modal_bottom_sheet: ^3.0.0-pre
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  very_good_analysis: ^5.0.0+1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/sf_pro_display_regular.otf
    - family: SFProMedium
      fonts:
        - asset: assets/fonts/sf_pro_display_medium.otf
    - family: SFProBold
      fonts:
        - asset: assets/fonts/sf_pro_display_bold.otf
    - family: SFProItalic
      fonts:
        - asset: assets/fonts/sf_pro_display_black_italic.otf
    - family: SFProHeavyItalic
      fonts:
        - asset: assets/fonts/sf_pro_display_heavy_italic.otf
